version: '3.7'

services:
  php-fpm:
    image: fromsi/php-fpm
    volumes:
      - ../:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www
      - ./nginx/:/etc/nginx/conf.d
      - ./nginx/vhosts:/etc/nginx/vhosts
    depends_on:
      - php-fpm
  mariadb:
    image: yobasystems/alpine-mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=docker
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=hever
    volumes:
      - ./adminer/adminer.css:/var/www/html/designs/hever/adminer.css
  mongo:
    image: mvertes/alpine-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
  redis:
    image: redis:rc-alpine
