version: '3.7'
services:
  mariadb:    
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb:/var/lib/mysql
  mongo:
    image: mvertes/alpine-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/data/db
  redis:
    image: redis:rc-alpine
    volumes:
      - ./redis:/data

  adminer:
    image: dehy/adminer
    ports:
      - 8001:80
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - 8002:8081
