version: '3.7'
services:
  php-fpm:
    image: fromsi/php-fpm
    volumes:
      - ../:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  db:
    image: yobasystems/alpine-mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "6080:3306"
  adminer:
    image: dehy/adminer
    ports:
      - 8001:80
