version: '3.7'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
  mariadb:
    ports:
      - "3306:3306"
  adminer:
    ports:
      - "8080:8080"
  mongo:
    ports:
      - 27017:27017
  redis:
    ports:
      - 6379:6379
  mongo-express:
    ports:
      - 8081:8081
